### PR TITLE
Make RS485Class a constructor arg to ModbusRTUClientClass and ModbusRTUServerClass

### PR DESCRIPTION
**Pull request by sandeepmistry**
This is an alternative to pull request #11 

Instead of having a parameter to `begin(...)` a new `ModbusRTUClientClass` or `ModbusRTUServerClass` instance can be declared with an alternative `RS485Class` instance.

### CODE REVIEW

**Comment by nud** [comment]
What about going even further and calling it "transport" rather than "rs485"? I myself would very much like to have a RS232 transport as well.

**Comment by willwilder** [comment]
Have you had success getting this to work? I have a use case for specifying the hardware serial port I want to use, trying to get the Sparkfun AST-CAN485 running as a ModbusRTU slave. The RS-485 chip is hard wired to Serial1.

**Comment by OpZed** [comment]
I'd also like to see the interface abstracted from the protocol.  For use with RS232 and also the native USB Serial Port (which is typically only used for debugging with "Serial Monitor").

**Comment by cheetor5923** [comment]
I like this idea... Realistically the best option would be to have each layer of the OSI model as a separate modular bit of code.

**Comment by SWoto** [comment]
@sandeepmistry, I've tested your code with the KitchenSink's example, [ModbusRTUServerKitchenSink](https://github.com/arduino-libraries/ArduinoModbus/tree/master/examples/RTU/ModbusRTUServerKitchenSink)  and [ModbusRTUClientKitchenSink](https://github.com/arduino-libraries/ArduinoModbus/tree/master/examples/RTU/ModbusRTUClientKitchenSink).

### Steps:
1. Download [your commit - ea16c79920ec62cc96d1c0ca8be973d8cb853559](https://github.com/arduino-libraries/ArduinoModbus/tree/ea16c79920ec62cc96d1c0ca8be973d8cb853559)
2. Change Serial port

```Cpp
[...] some code before here 

RS485Class _RS485(Serial2, txPin, dePin, rePin);

void setup() {
  ModbusRTUClient = ModbusRTUClientClass(_RS485);

[...] some code after here 
```

3. Run Server in one board and client in another.

### Results:
```
16:17:10.627 -> Writing Coil values ... success
16:17:10.667 -> Reading Coil values ... success
16:17:10.667 -> 0 0 0 0 0 0 0 0 0 0 
16:17:10.667 -> Reading Discrete Input values ... success
16:17:10.708 -> 0 0 0 0 0 0 0 0 0 0 
16:17:10.708 -> Writing Holding Registers values ... failed! Connection timed out
16:17:11.715 -> Reading Input Register values ... failed! Connection timed out
16:17:12.717 -> Reading input register values ... failed! Connection timed out
16:17:18.754 -> 
16:17:18.754 -> Writing Coil values ... success
16:17:18.754 -> Reading Coil values ... success
16:17:18.787 -> 1 1 1 1 1 1 1 1 1 1 
16:17:18.787 -> Reading Discrete Input values ... success
16:17:18.787 -> 1 1 1 1 1 1 1 1 1 1 
16:17:18.787 -> Writing Holding Registers values ... failed! Connection timed out
16:17:19.840 -> Reading Input Register values ... failed! Connection timed out
16:17:20.840 -> Reading input register values ... failed! Connection timed out
```

If I turn the Server off, I get all the results as `Connection timed out`, so they are communicating.

I've also changed `Serial2` to `Serial3` and I also receive `Connection timed out` every time, so the modification worked just fine.

### Sugestion
Would be really good to have this option in the `ModbusRTUServer` too.

**Comment by SWoto** [comment]
@sandeepmistry, please let me know if there are any other tests that you would like me to run.

**Comment by SWoto** [comment]
This branch is working like a charm.
```
RS485 = RS485Class(Serial2, Serial2, txPin, dePin, rePin);
ModbusRTUClient = ModbusRTUClientClass(_RS485);
```

Solves the problem that the RS485 class is hardcoded in the ArduinoModbus.

@sandeepmistry

**Comment by Brianthechemist** [comment]
I'm about to do this one myself.  Is there any reason it won't work with ModbusRTUServer? Looks like the same tweaks to the code would do it.

**Pull request closed without merging**
